language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run build
  - npm run export
deploy:
  skip_cleanup: true
  local_dir: dist/
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: source
